### ISSUE TITLE
Include tests for failure and coercion

### ISSUE THREAD

**Issue by noamross** [pboesu/rucrdtw#2]
Tests are included and all tests pass, and coverage is high.  I note that where coverage is missing, it is largely because there are not tests that coercion and error handling occur properly ([example](https://codecov.io/gh/pboesu/rucrdtw/src/ad49dddc2eb0c12943a6f057df696b59d9e7e76d/R/ucrdtw.R#L81...82)).  I suggest adding tests to cover these cases, e.g. using `expect_error()`.

This issue is part of JOSS review https://github.com/openjournals/joss-reviews/issues/100

**Comment by pboesu** [comment]
added tests for missing input files, wrong input types and dimensions, and columnwise data input for vm methods
(Commits up to 8d00a9c1083bb1652353c4267a3269684680057c)

**Comment by noamross** [comment]
Looks good!
