### ISSUE TITLE
Exporting a C++ level interface

### ISSUE THREAD

**Issue by noamross** [pboesu/rucrdtw#4]
As this low-level package that may be used as a building block for other work, I suggest exporting the C++ functions so that other packages may import them the `// [[Rcpp::interfaces(r, cpp)]]` attribute marker will generate exportable C++ code.  Other packages will then be able to use the C++ functions without R overhead simply by referring to **rucrdtw** in the `LinkingTo:` field in their DESCRIPTION file.

This issue is part of JOSS review https://github.com/openjournals/joss-reviews/issues/100

**Comment by pboesu** [comment]
`// [[Rcpp::interfaces(r, cpp)]]` added in 140dd3a240d2978524308b2e8bb7432e56392551

I'm new to Rcpp, so I am not entirely sure how to test whether this worked.

**Comment by noamross** [comment]
Looks good.  The important thing is the new files generated in `inst/include`, which can now be included as header files in any other package.
