### ISSUE TITLE
By CRAN standards, ucrdtw_vv should have a pure R source counterpart

### ISSUE THREAD

**Issue by ghost** [pboesu/rucrdtw#6]
Functions like ucrdtw_mv call ucrdtw_vv. The latter only has a C++ version, not an **R** source counterpart. CRAN standards encourage an **R** counterpart for each and every part of a package, even if the execution time is unbearably slow.

**Comment by pboesu** [comment]
I'm unaware of this policy, nor is this common practice in my experience. Could you point to the relevant section in the [R Extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)?

If you want to understand what the compiled functions are doing you can have a look at the [C++ sources](https://github.com/pboesu/rucrdtw/tree/master/src) and/or the the paper by [Rakthanmanon et al.](http://doi.org/10.1145/2339530.2339576) which describes the algorithm in great detail.

 Rakthanmanon et al. (2012). Searching and mining trillions of time series subsequences under dynamic time warping. SIGKDD http://doi.org/10.1145/2339530.2339576

**Comment by ghost** [comment]
Philipp,

You may be correct, although that has not been my experience.  Indeed,
many times, consulting *R* code is the only way I know how to determine
what some package is actually complaining about, and fixing it.
Thank you for the reference to Rakthanmanon, et al.  I'll consult that
deeply, although my interest is really to implement the Matrix Profile
version of all this, and not, strictly speaking, *rucrdtw*. See
http://www.cs.unm.edu/~mueen/FastestSimilaritySearch.html
To that end, I'm intending to produce versions of that in Python 3,
and in *R*, although I by no means intend to produce a publicly
usable package.
Best of luck,

  - Jan


On Sat, May 6, 2017, at 13:56, Philipp Boersch-Supan wrote:
> I'm unaware of this policy, nor is this common practice in my
> experience. Could you point to the relevant section in the R
> Extensions manual[1]?> If you want to understand what the compiled functions are doing you
> can have a look at the C++ sources[2] and/or the the paper by
> Rakthanmanon et al.[3] which describes the algorithm in great detail.> Rakthanmanon et al. (2012). Searching and mining trillions of time
> series subsequences under dynamic time warping. SIGKDD
> http://doi.org/10.1145/2339530.2339576> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[4], or mute the thread[5].> 


Links:

  1. https://cran.r-project.org/doc/manuals/r-release/R-exts.html
  2. https://github.com/pboesu/rucrdtw/tree/master/src
  3. http://doi.org/10.1145/2339530.2339576
  4. https://github.com/pboesu/rucrdtw/issues/6#issuecomment-299656044

**Comment by pboesu** [comment]
You are most welcome to prepare a pull request with an R translation of the C++ sources. 
But as this is neither a CRAN requirement, nor adds functionality to the package, I'm afraid that this is not anything I will tackle any time soon.
